export type LibreTranslateApiSupportedLanguage = {
  code: string;
  name: string;
  countryCode: string;
};

export const LIBRE_TRANSLATE_API_SUPPORTED_LANGUAGES = [
  { code: "ar", name: "Arabic", countryCode: "SA" },
  { code: "bg", name: "Bulgarian", countryCode: "BG" },
  { code: "bn", name: "Bengali", countryCode: "BD" },
  { code: "ca", name: "Catalan", countryCode: "AD" },
  { code: "cs", name: "Czech", countryCode: "CZ" },
  { code: "da", name: "Danish", countryCode: "DK" },
  { code: "de", name: "German", countryCode: "DE" },
  { code: "el", name: "Greek", countryCode: "GR" },
  { code: "en", name: "English", countryCode: "US" },
  { code: "eo", name: "Esperanto", countryCode: "IS" },
  { code: "es", name: "Spanish", countryCode: "ES" },
  { code: "et", name: "Estonian", countryCode: "EE" },
  { code: "fa", name: "Persian", countryCode: "IR" },
  { code: "fi", name: "Finnish", countryCode: "FI" },
  { code: "fr", name: "French", countryCode: "FR" },
  { code: "ga", name: "Irish", countryCode: "IE" },
  { code: "he", name: "Hebrew", countryCode: "IL" },
  { code: "hi", name: "Hindi", countryCode: "IN" },
  { code: "hu", name: "Hungarian", countryCode: "HU" },
  { code: "id", name: "Indonesian", countryCode: "ID" },
  { code: "it", name: "Italian", countryCode: "IT" },
  { code: "ja", name: "Japanese", countryCode: "JP" },
  { code: "ko", name: "Korean", countryCode: "KR" },
  { code: "lt", name: "Lithuanian", countryCode: "LT" },
  { code: "lv", name: "Latvian", countryCode: "LV" },
  { code: "ms", name: "Malay", countryCode: "MY" },
  { code: "nb", name: "Norwegian", countryCode: "NO" },
  { code: "nl", name: "Dutch", countryCode: "NL" },
  { code: "pl", name: "Polish", countryCode: "PL" },
  { code: "pt", name: "Portuguese", countryCode: "PT" },
  { code: "ro", name: "Romanian", countryCode: "RO" },
  { code: "ru", name: "Russian", countryCode: "RU" },
  { code: "sk", name: "Slovak", countryCode: "SK" },
  { code: "sl", name: "Slovenian", countryCode: "SI" },
  { code: "sq", name: "Albanian", countryCode: "AL" },
  { code: "sr", name: "Serbian", countryCode: "RS" },
  { code: "sv", name: "Sweden", countryCode: "SE" },
  { code: "th", name: "Thai", countryCode: "TH" },
  { code: "tl", name: "Tagalog", countryCode: "PH" },
  { code: "tr", name: "Turkish", countryCode: "TR" },
  { code: "uk", name: "Ukrainian", countryCode: "UA" },
  { code: "ur", name: "Urdu", countryCode: "PK" },
  { code: "vi", name: "Vietnamese", countryCode: "VN" },
  { code: "zh", name: "Chinese", countryCode: "CN" },
] as LibreTranslateApiSupportedLanguage[];
