name: Api

on: [push]

defaults:
  run:
    working-directory: api

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changes:
              - api/**
              - .github/workflows/api.yml

  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes == 'true' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Copy .env
        run: |
          cp .env.sample .env
      - name: Test
        run: |
          npm run test
      - name: Test e2e
        run: |
          npm run test:e2e
      - name: Build
        run: |
          npm run build
