name: Webapp

on: [push]

defaults:
  run:
    working-directory: webapp

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changes:
              - webapp/**
              - .github/workflows/webapp.yml

  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes == 'true' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test
      - name: Build
        run: |
          npm run build
